server.port=8087
spring.datasource.url=jdbc:mysql://localhost:3306/finflow_app_db
spring.datasource.username=root
spring.datasource.password=TanmoyPass4
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
