# auth-service.properties
server.port=${AUTH_SERVICE_PORT:8085}

spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/finflow_auth_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

jwt.secret=${JWT_SECRET}
gateway.secret=${GATEWAY_SECRET}
